fieldLayouts:
  78fe7fa0-0878-4c4f-bf38-f8146a1ed29a:
    tabs:
      -
        elements:
          -
            fieldUid: ee9b07ba-aa4e-4436-9eb3-d58314d33131 # Navigation
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Content
        sortOrder: 1
handle: header
name: Header
