enableVersioning: true
handle: aboutUs
name: 'About Us'
propagationMethod: all
siteSettings:
  7c70816a-1fa8-4637-b04e-5872560bec6d: # Craft CMS Bruno
    enabledByDefault: true
    hasUrls: true
    template: general
    uriFormat: about-us
type: single
